### ISSUE TITLE
tempoross plugin leaks memory

### ISSUE THREAD

**Issue by Adam-** [nmlynch94/runelite-external-plugins#4]
The tempoross plugin holds game objects and tiles in memory from past scenes in `totemMap` because it is not cleared on LOADING state. A recent change we made to the client holds a backreference from Tile to Scene to support multiple concurrent scenes. This causes the tempoross plugin to keep multiple past Scenes alive, eventually leading to extreme memory usage and OOM. Fix the plugin to clear any references to GameObjects or Tiles when a new scene is loaded.

**Comment by nmlynch94** [comment]
Was able to reproduce by setting my heap maximum to 700mb and world hopping in Shipyard (this is what the original reporter was doing). Cleared on LOADING like you suggested, and now the heap stays under 50% full at 700mb while doing the same thing [b00bac80a25cda4cfa552d9397988f3cc9796461](https://github.com/nmlynch94/runelite-external-plugins/commit/b00bac80a25cda4cfa552d9397988f3cc9796461).
