### ISSUE TITLE
Unable to remove Jagex Launcher credentials from RuneLite

### ISSUE THREAD

**Issue by JulianLee93** [nmlynch94/runelite-external-plugins#5]
I followed the [instructions](https://github.com/runelite/runelite/wiki/Using-Jagex-Accounts) to login using my Jagex account while working on RuneLite development projects. Now every time I launch RuneLite, my account credentials are automatically included, so my account is already logged in and I am unable to access any of my non-Jagex accounts via RuneLite. For example, if I'm logged into my account on RuneLite and I open a second instance of RuneLite, the only option I am given is a "Play" button for the same account, which is already logged in.

How can I remove the authentication credentials to run RuneLite as it had been before the configurations?

**Comment by nmlynch94** [comment]
@JulianLee93 I think you made this issue in the wrong repo.
