### ISSUE TITLE
Tempoross plug in not currently showing for me but is for others

### ISSUE THREAD

**Issue by fhSwamp3r** [nmlynch94/runelite-external-plugins#6]
Right so the problem is temp plugin is currently at the time of this post not showing for any of my accounts but is for cc members and others on discorrd on there profiles.. tried a wipe and i cant seem to find a fix

**Comment by avershave** [comment]
it's currently disabled. check the plugin hub repo in runelite.

**Comment by nmlynch94** [comment]
I have a fix working and will be making a PR today.

**Comment by nmlynch94** [comment]
fixed in https://github.com/nmlynch94/runelite-external-plugins/commit/b00bac80a25cda4cfa552d9397988f3cc9796461

**Comment by nmlynch94** [comment]
@fhSwamp3r It should be re-enabled now.
